version: "3.8"
services:
  app:
    platform: linux/amd64
    image: registry.gitlab.com/jostechnology/thaimui-pms-web-dev:${TAG}
    container_name: thaimui-pms-web
    ports:
      - "7002:5173"
    environment:
      - VITE_FRONT_API=${VITE_FRONT_API}
      - VITE_GOOGLE_API=${VITE_GOOGLE_API}
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
